### ISSUE TITLE
Geyser Support?

### ISSUE THREAD

**Issue by Tydium** [IdreesInc/Celeste#2]
I tried on a 1.18 server and it seems bedrock players are unable to see shooting stars (Tried on Switch). Maybe you can add a config option that can somewhat make it visible for bedrock player? Falling stars work though, which I gotta say it is pretty cool. Perhaps a different particle for bedrock edition?

**Comment by IdreesInc** [comment]
It's possible that the render distance for particles in Bedrock edition is shorter than it is for Java edition. The most recent plugin update allows you to modify the min and max height of the shooting stars, try reducing that and see what happens.
It's also possible that Geyser's has some bugs with displaying particles, 1.18 was only just released and I wouldn't be surprised if there are still some incompatibilities.

**Comment by Tydium** [comment]
Alrighty thanks for the input. Ill try this out when I get home today. Thank you
