### ISSUE TITLE
Items with NBT data

### ISSUE THREAD

**Issue by USBCharger** [IdreesInc/Celeste#3]
Hey, it'd be really useful if there was an option to add items that had NBT data, as crate keys or crates could be dropped.

**Comment by 0elek** [comment]
Agreed.

**Comment by Trico-Everfire** [comment]
It's actually a feature required for my purposes, I forked the project and PR it if i succeed before @IdreesInc  does.

**Comment by IdreesInc** [comment]
Changes have been merged into main and released: https://www.spigotmc.org/resources/celeste.81862/
